# Generated by Django 2.2.3 on 2019-07-29 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('imgpremises', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.CharField(max_length=1000)),
                ('whyus', models.CharField(max_length=750)),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cl', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('created', 'Created'), ('recruitmentinprogress', 'RecruitmentInProgress'), ('expired', 'Expired')], max_length=50)),
                ('perks', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('interviewselectioncriteria', models.CharField(max_length=500)),
                ('jobdescription', models.CharField(max_length=1000)),
                ('jobtags', models.CharField(max_length=250)),
                ('joblink', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='jpl.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('doj', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('salaryexpected', models.BigIntegerField()),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('amountpaid', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobvp', to='jpl.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rd', models.FileField(null=True, upload_to='')),
                ('js', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jpl.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coverletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverletter', to='jpl.CoverLetter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobja', to='jpl.Job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to='jpl.Jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jpl.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='coverletter',
            name='js',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='jpl.Jobseeker'),
        ),
        migrations.AddConstraint(
            model_name='jobseeker',
            constraint=models.UniqueConstraint(fields=('usr',), name='unique_jobseeker'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'jobseeker'), name='unique_appln'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('usr',), name='unique_company'),
        ),
    ]
